# Generated by Django 5.1.2 on 2024-11-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_category_book_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book_count',
        ),
    ]
