# Generated by Django 5.1.2 on 2024-12-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_remove_category_book_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='author',
            name='book_count',
        ),
        migrations.RemoveField(
            model_name='author',
            name='fav_book_count',
        ),
    ]
