# Generated by Django 5.1.2 on 2025-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_remove_author_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(null=True),
        ),
        migrations.AlterModelTable(
            name='author',
            table='BookApp_author_2',
        ),
        migrations.AlterModelTable(
            name='book',
            table='BookApp_book_2',
        ),
        migrations.AlterModelTable(
            name='category',
            table='BookApp_category_2',
        ),
        migrations.AlterModelTable(
            name='favbook',
            table='BookApp_favbook_2',
        ),
    ]
